site_name: NearIT iOS
theme: readthedocs
extra_css : ["css/nearitdocs.css"]
pages:
    - 'Getting started' : 'index.md'
    - 'User Guide' :
        - 'Installation' : 'installation.md'
        - 'Location Based Notifications' : 'location-based-notifications.md'
        - 'Push Notifications' : 'push-notifications.md'
        - 'In-app Content' : 'handle-content.md'
        - 'User Profiling' : 'user-profilation.md'
    - 'Other resources' :
        - 'Testing' : 'testing.md'
        - 'Logging' : 'logging.md'
        - 'Local background notification' : 'local-background-notification.md'
